---
title: "Anaálise Tempos Questão 05"
output: html_notebook
---

```{r}
knitr::opts_chunk$set(warning = FALSE)
library(ggplot2)
library(plotly)
```

```{r}
temposList <- read.csv("/Users/mattheusbrito/git/paradigma-concorrente/questao5/tempos_list.csv")
temposMap <- read.csv("/Users/mattheusbrito/git/paradigma-concorrente/questao5/tempos_map.csv")
mediasList <- read.csv("/Users/mattheusbrito/git/paradigma-concorrente/questao5/medias_list.csv")
mediasMap <- read.csv("/Users/mattheusbrito/git/paradigma-concorrente/questao5/medias_map.csv")
```



```{r}
analiseTempoList <- temposList %>%
  group_by(threads)



analiseTempoList <- analiseTempoList[order(analiseTempoList$put_synch, decreasing = FALSE)]
analiseTempoList$indexThreads <- factor(analiseTempoList$threads, levels = analiseTempoList$threads)


analiseTempoList %>%
  plot_ly(x= ~indexThreads, y= ~put_synch, type= "scatter", mode= "lines+markers") %>%
  layout(title="Tempo do Put Synchronized", xaxis=list(title="Número de Threads"), yaxis=(title="Tempo gasto"),
         barmode="stack")
```






